name: cmatrix_app
description: "CMatrix: AI-powered EdTech Platform"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    # flutter_launcher_icons: ^0.13.1

  # UI and Fonts
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  fluttertoast: ^8.2.12  # or latest stable

  # Firebase Core Services
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

  # Authentication
  google_sign_in: ^6.3.0
  flutter_secure_storage: ^9.2.2
  sign_in_button: ^3.2.0

  # Utilities
  http: ^1.2.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  image_picker: ^1.1.2

  # Video/Lecture Support
  youtube_player_flutter: ^9.0.1

  # State Management (Optional - recommended for scalability)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:

  uses-material-design: true

  assets:
    - lib/images/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

