// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDYvr1NeBHyPAKbtTgnd-wQc1dySLrLA',
    appId: '1:344193158201:web:e0681a116dd03796a411e8',
    messagingSenderId: '344193158201',
    projectId: 'cmatrix-app',
    authDomain: 'cmatrix-app.firebaseapp.com',
    databaseURL: 'https://cmatrix-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmatrix-app.firebasestorage.app',
    measurementId: 'G-WZEBQ11JWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn5r0Wa7y8G_jI5e_c8kCb65User93DE0',
    appId: '1:344193158201:android:787870a6f613b327a411e8',
    messagingSenderId: '344193158201',
    projectId: 'cmatrix-app',
    databaseURL: 'https://cmatrix-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmatrix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9kDYHg1bh3DbqqACJF2UNvUzpfO_TM8k',
    appId: '1:344193158201:ios:dfe8c71d577cfaa3a411e8',
    messagingSenderId: '344193158201',
    projectId: 'cmatrix-app',
    databaseURL: 'https://cmatrix-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmatrix-app.firebasestorage.app',
    iosClientId: '344193158201-njhka1uflnba4bdnpqpr9tncri7tjbr2.apps.googleusercontent.com',
    iosBundleId: 'com.angie.edulink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9kDYHg1bh3DbqqACJF2UNvUzpfO_TM8k',
    appId: '1:344193158201:ios:28514476701ef794a411e8',
    messagingSenderId: '344193158201',
    projectId: 'cmatrix-app',
    databaseURL: 'https://cmatrix-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmatrix-app.firebasestorage.app',
    iosClientId: '344193158201-src3g5nhhj0spufkk8rgbd5lvojpboum.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhDYvr1NeBHyPAKbtTgnd-wQc1dySLrLA',
    appId: '1:344193158201:web:4fe860f79a584b1ba411e8',
    messagingSenderId: '344193158201',
    projectId: 'cmatrix-app',
    authDomain: 'cmatrix-app.firebaseapp.com',
    databaseURL: 'https://cmatrix-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmatrix-app.firebasestorage.app',
    measurementId: 'G-DMT5F513SV',
  );
}
